import Head from "next/head";
import { useState } from "react";

export default function Home() {
  const [user, setUser] = useState("");
  return (
    <div>
      <Head>
        <title>Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <input
          type="text"
          placeholder="Your Github user"
          onChange={(e) => {
            setUser(e.currentTarget.value);
          }}
        />
        <a href={`${user}/repos`}>Check</a>
      </div>
    </div>
  );
}
